model:
    __type__: configs.Transformer_Config
    tmix: qwen2
    classname: qwen2
    attention_type: rwkv
    ctx_len: 512 #4096
    vocab_size: 151936
    vocab_padding_idx: 151646 
    num_key_value_heads: 2
    head_size: 128
    n_embd: 2048
    dim_ffn: 11008
    n_layer: 36
    rope:
        __type__: configs.RoPE_Config
        base: 1000000.0

train:
  teacher:
    path: out/qwen2.5-3B.pth
    model:
      __type__: configs.Transformer_Config
      #tmix: qwen2
      classname: qwen2
      ctx_len: 512 #4096
      vocab_size: 151936
      vocab_padding_idx: 151646 
      num_key_value_heads: 2
      head_size: 128
      n_embd: 2048
      dim_ffn: 11008
      n_layer: 36
      rope:
          __type__: configs.RoPE_Config
          base: 1000000.0
